config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root   'home#index'

  get    '/signup',         to: 'people#new'
  post   '/signup',         to: 'people#create'
  get    '/profile',        to: 'people#show'
  get    '/profile/edit',   to: 'people#edit'
  patch  '/profile/edit',   to: 'people#update'
  delete '/delete_account', to: 'people#destroy'

  get    '/login',          to: 'sessions#new'
  post   '/login',          to: 'sessions#create'
  delete '/logout',         to: 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/views/layouts/_header.html.erb
<% if person_is_logged_in? %>
  <%= link_to t('person.profile.link'), profile_path %>
  <%= link_to t('person.edit.link'), profile_edit_path %>
  <%= link_to t('logout.link'), logout_path, method: :delete %>
<% else %>
  <%= link_to t('login.link'), login_path %>
  <%= link_to t('signup.link'), signup_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeopleOnRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "notification notification--#{message_type}") %>
    <% end %>

    <%= render 'layouts/header' %>

    <%= yield %>
  </body>
</html>